version: 1.0.{build}

configuration:
  - Release

os: Visual Studio 2017
image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - PYTHON: C:\Python36
      PYTHON_VERSION: 36
      TAG_SCENARIO: False
    - PYTHON: C:\Python37
      PYTHON_VERSION: 37
      TAG_SCENARIO: True

matrix:
  fast_finish: true

for:
-
  matrix:
    only:
      - TAG_SCENARIO: True
    skip_non_tags: True

install:
  - ps: choco install -y --no-progress --allow-empty-checksums -r swig
  - IF "%platform%" == "x64" SET PYTHON=%PYTHON%-x64
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install pip --upgrade --user

  - echo %PYTHON_VERSION%
  - IF "%PYTHON_VERSION%" == "35" python -m pip install .thirdparty/Shapely-1.6.4.post2-cp35-cp35m-win_amd64.whl
  - IF "%PYTHON_VERSION%" == "36" python -m pip install .thirdparty/Shapely-1.6.4.post2-cp36-cp36m-win_amd64.whl
  - IF "%PYTHON_VERSION%" == "37" python -m pip install .thirdparty/Shapely-1.6.4.post2-cp37-cp37m-win_amd64.whl

  - python -m pip install -r requirements_setup.txt
  - pip install twine

before_build:
  - set generator="Visual Studio 15 2017"
  - IF "%platform%" == "x64" set generator="Visual Studio 15 2017 Win64"
  - git fetch --tags
  - git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata


build_script:
  - python setup.py bdist_wheel -G %generator%
  - ps: pip install $(ls dist/*.whl | % {$_.FullName})
  - pip freeze --all

test_script:
  - pytest

deploy_script:
  - echo "Upload to PYPI if tag..."
  - ps: |
        Write-Host "TAG: $env:APPVEYOR_REPO_TAG"
        If ($env:APPVEYOR_REPO_TAG -eq "false") { return }

        Write-Host "Uploading wheels to pypi"
        Invoke-Expression "twine upload -u jcrivenaes --password $env:PYPIPASSWD --skip-existing dist/*"
        If ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
