version: 1.0.{build}

configuration:
  - Release

os: Visual Studio 2015
image: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - PYTHON: C:\Python35
      PYTHON_VERSION: 35
    - PYTHON: C:\Python36
      PYTHON_VERSION: 36
    - PYTHON: C:\Python37
      PYTHON_VERSION: 37

matrix:
  fast_finish: true

install:
  - ps: choco install -y --no-progress --allow-empty-checksums -r swig --version 3.0.9
  - IF DEFINED PYTHON (IF "%platform%" == "x64" SET PYTHON=%PYTHON%-x64)
  - IF DEFINED PYTHON SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - IF DEFINED PYTHON pip install --upgrade
  numpy
  scipy
  pytest
  setuptools
  setuptools_scm
  hypothesis
  twine
  wheel

before_build:
  - set generator="Visual Studio 14 2015"
  - IF "%platform%" == "x64" set generator="Visual Studio 14 2015 Win64"
  - git submodule update --init --recursive
  - git fetch --tags

build_script:
  - git describe
  - IF DEFINED PYTHON python setup.py bdist_wheel -G %generator%
  - ps: popd

# before_deploy:
#     - ps: pushd python

# after_deploy:
#     - ps: popd

# deploy_script:
#     - ps: |
#           Write-Host "TAG: $env:APPVEYOR_REPO_TAG"
#           If ($env:APPVEYOR_REPO_TAG -eq "false") { return }
#           Write-Host "Uploading wheels to pypi"
#           Invoke-Expression "twine upload -u statoil-travis --skip-existing dist/*"
#           If ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
