version: 2


python:
  version: 3.6
  install:
    - method: setuptools
      path: .
    - requirements: requirements.txt
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
