language: python

addons:
  apt:
    packages:
    - swig

python:
    - '2.7'
    - '3.6'

before_script:
    - git clone https://git@github.com/equinor/xtgeo-testdata.git ../xtgeo-testdata

script:
    - python setup.py test
