language: python

python:
- 3.6

os:
- linux

git:
  depth: false

addons:
  apt:
    packages:
    - swig

services: docker

sudo: required

env:
  global:
  - REPO_DIR=.
  - UNICODE_WIDTH=32
  - PLAT=x86_64
  - MB_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - VERSION=$(echo $TRAVIS_TAG)
  - BUILD_DEPENDS="cmake numpy==1.10.4 pandas==0.19"
  - CONFIG_PATH=scripts/config.sh
  - TEST_DEPENDS="pytest"

matrix:
  fast_finish: true
  exclude:
  - python: 3.6
  include:
  - os: linux
    env: MB_PYTHON_VERSION=2.7
  - os: linux
    env: MB_PYTHON_VERSION=3.4
  - os: linux
    env: MB_PYTHON_VERSION=3.5
  - os: linux
    env: MB_PYTHON_VERSION=3.6
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.7
      - SOURCEDEPLOY=1
      - BUILD_DEPENDS="cmake numpy>=1.14 pandas"

before_install:
  - echo "PWD is $PWD"
  - unset -f pushd
  - unset -f popd
  - git clone https://github.com/matthew-brett/multibuild
  - ls -l
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - pip install bandit
  - build_wheel $REPO_DIR $PLAT

before_script:
  - bandit -c bandit.yml -r src/xtgeo

script:
- install_run $PLAT
- mv wheelhouse dist

after_success:
- ls -l ${TRAVIS_BUILD_DIR}/dist

before_deploy:
- pip install numpy

deploy:
  provider: pypi
  skip_cleanup: true
  skip_upload_docs: true
  distributions: build
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: True
    repo: equinor/xtgeo
    # condition: -z $SOURCEDEPLOY
