language: python

addons:
  apt:
    packages:
    - swig

python:
    - '2.7'
    - '3.4'
    - '3.6'

before_script:
    - git clone https://c625a677ff258e52690537553ba18a1b845070be@github.com/equinor/xtgeo-testdata.git ../xtgeo-testdata

script:
    - make cc
    - make dist
    - make test
