language: python

python:
- 3.6

os:
- linux

if: branch=master

services: docker

sudo: required

env:
  global:
  - REPO_DIR=.
  - UNICODE_WIDTH=32
  - PLAT=x86_64
  - MB_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - VERSION=$(echo $TRAVIS_TAG)
  - BUILD_DEPENDS="cmake numpy"
  - CONFIG_PATH=scripts/config.sh
  - TEST_DEPENDS="pytest"

matrix:
  fast_finish: true
  exclude:
  - python: 3.6
  include:
  - os: linux
    env: MB_PYTHON_VERSION=2.7
  - os: linux
    env: MB_PYTHON_VERSION=3.6
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.7
      - SOURCEDEPLOY=1

before_install:
- echo "PWD is $PWD"
- unset -f pushd
- unset -f popd
- git clone https://github.com/matthew-brett/multibuild
- ls -l
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install

install:
- build_wheel $REPO_DIR $PLAT

script:
- install_run $PLAT
- mv wheelhouse dist

after_success:
- ls -l ${TRAVIS_BUILD_DIR}/dist

before_deploy:
- ls -l dist
- pip install numpy

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  skip_upload_docs: true
  distributions: build
  user: jcrivenaes
  password:
    secure: E2pm0/4ROnEJLcSTCd3YcLpswf5nqCJxfZGbIAjPe2/ZCrMcTqRapSgn3YePewqZYumi/WHIUPfBxGv/hNP9czKW9LUByNBFm2XNxc+OafL/h4XVDd92UzH4tfWwIl5+0JnSuToWLBU2r267+ALVz0FVnrYd/itLMrbqAh8HaSkX6/kAt0sPxEjx7O50KPg4NOomHcAWDaTk7UWqnmtYUXlZf1NhdTD/XQh09JCB+7dM6EzyEIU7HjdNF5xyHVoNNuBhc7IvyqLCjMFCHsyG4WMavvP8MXgQgdPWGokRWUc79T6GfiOkUjjnxsidhFpVAtr0uB0sKnEciwdvlPsbNsRPiC4i7128GyqAC2+CjhZXhoxY+UogjI9Rg6Cu7FuQYGXDv0UBTdpVhV9+7CgM4DZOkOU1IgdQzgnHD9HNPPTsXPNFwML5USO2M8Gs+vNM0wEcbdJuWZAWVvQRTaL/Au+9YnyzIgYOngSYmfQrs96T1aYY4FdJaxHxg8fEOD3SyNkohZiMc4zmWo4Sb+rE8A3DqCpuvNe4yIPQzBAZljfhpbsC3vJciPimYroKXXOP9STp4NB2MRQpvIb7e2txR0N2NkipDz8o8Oi2pqKxQRnkmK1+3H6OZEITojQGMdgJ1CNFVZReokOZHnWxsnDoG2mn63PShDguLQD5X1m2Ewg=
  # on:
  #   tags: False
    # condition: -z $SOURCEDEPLOY
