language: python

python:
  - 3.6

os:
  - linux

git:
  depth: false

addons:
  apt:
    packages:
      - swig

services: docker

sudo: required

if: (branch =~ /^dev/) OR (repo == equinor/xtgeo)

env:
  global:
    - REPO_DIR=.
    - UNICODE_WIDTH=32
    - PLAT=x86_64
    - MB_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
    - VERSION=$(echo $TRAVIS_TAG)
    - BUILD_DEPENDS="cmake==3.13.3"
    - CONFIG_PATH=scripts/config.sh
    - TEST_DEPENDS="pytest"

matrix:
  fast_finish: true
  exclude:
    - python: 3.6
  include:
    - os: linux
      env: MB_PYTHON_VERSION=2.7
    - os: linux
      env: MB_PYTHON_VERSION=3.4
      if: tag IS present
    - os: linux
      env: MB_PYTHON_VERSION=3.5
    - os: linux
      env: MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - SOURCEDEPLOY=1

before_install:
  - echo "PWD is $PWD"
  - unset -f pushd
  - unset -f popd
  - git clone https://github.com/matthew-brett/multibuild
  - ls -l
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - pip install bandit
  - build_wheel $REPO_DIR $PLAT

before_script:
  - bandit -c bandit.yml -r src/xtgeo

script:
  - install_run $PLAT
  - mv wheelhouse dist

after_success:
  - ls -l ${TRAVIS_BUILD_DIR}/dist

before_deploy:
  - pip install numpy

deploy:
  - provider: pypi
    skip_cleanup: true
    skip_upload_docs: true
    distributions: build
    user: statoil-travis
    password:
      secure: "fN4ZaDGqv6lWwRWWHgBawE5L6h+9Epkn6HfgBCMKpMA5WG8F0H2vxDrP8+HnsNf7eVhr4Z6lG2k0pzpuJb9BUtpknORYPocREBp7sDOmxY/a/Y+3Q+1g1dXY6JcLJW8uQTANQSvVTd8b1QMP1FxoIsdxxk+65j/Pn5vjFNgEJu8d7JyJR2GWQ4YwLmODITWqmM6QBbs6vMPtDh6VwvJuArHmj/v0phoIQ0rBXshS5hdA78+nsIYE6RSBYuonBSCA6wcQq8bIvl3xugVvvEbJ3iqFObA/i5Xar8RRgea7xvVhaB27oRIkzlyg2kWAVUVkfWCJLvinn7VcBgJrfEJlfiaz8yHaQWjouGMdYAjEKWmZKpjJEMjJ3YgPymLKTIOmX5wVQE1NYcQt3TANg/NECB/t99K9Faidith6G58GVeAIRt+T564Ocr5ZXUxfWF35akWsbH8gBcPJLl9LHOOtYy1Wp7xs4t2aRzz9X0uNuL0C3WRYd7wLL8/fhXwPL/4dJTeHsyNp52vLLJ4ulqZRiDVEjq+dMniTKRrXXxuvhNTkR2b4BWIAdUj7bxY7EE2vEEFVfx2X5CzyAF10pTrbPJ85AJauWS9i7Xv8yyi9L+VTGw8jnVvg/hFmN99o7nPGG+BovdTK0zrhzRCmWNrv3BqJiDSsxtxPws4GUedhWBc="
    on:
      tags: True
      repo: equinor/xtgeo
      # condition: -z $SOURCEDEPLOY
  #- provider: pypi
  #  server: https://testpypi.python.org/legacy
  #  skip_cleanup: true
  #  skip_upload_docs: true
  #  distributions: build
  #  user: $PYPI_USER
  #  password: $PYPI_PASSWORD
  #  on:
  #    tags: True
  #    draft: True
  #    repo: equinor/xtgeo
  #    # condition: -z $SOURCEDEPLOY
