language: python

python:
- 3.6

os:
- linux

if: branch=master

services: docker

sudo: required

env:
  global:
  - REPO_DIR=.
  - UNICODE_WIDTH=32
  - PLAT=x86_64
  - MB_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - VERSION=$(echo $TRAVIS_TAG)
  - BUILD_DEPENDS="cmake numpy"
  - CONFIG_PATH=scripts/config.sh
  - TEST_DEPENDS="pytest"

matrix:
  fast_finish: true
  exclude:
  - python: 3.6
  include:
  - os: linux
    env: MB_PYTHON_VERSION=2.7
  - os: linux
    env: MB_PYTHON_VERSION=3.6
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.7
      - SOURCEDEPLOY=1

before_install:
- echo "PWD is $PWD"
- unset -f pushd
- unset -f popd
- git clone https://github.com/matthew-brett/multibuild
- ls -l
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install

install:
- build_wheel $REPO_DIR $PLAT

script:
- install_run $PLAT
- mv wheelhouse dist

after_success:
- ls -l ${TRAVIS_BUILD_DIR}/dist

before_deploy:
- ls -la dist
- pip install numpy
- apt-get -y install swig

deploy:
  provider: pypi
  skip_cleanup: true
  skip_upload_docs: true
  server: https://testpypi.python.org/legacy/
  distributions: build
  user: jcrivenaes
  password:
    secure: iaDeFdcmVFNNAfib4+3foleYJDdXwhyP3v4CM3ulUwT1oxXlKOAh8AmOof2FymuCwqkZ8hb1lxm5YZ8AxOJ9etzzezO6+vT9pBwqIHx1fKZ8zWp/zecukrn0m3O5gGZRAF
782VKH2u5utiZtH5oLrtPBnSi9nptJYVgAWjZnlFlZssJl9U3GnNcN+3XNaRX0LuiMB4U6m7eQkDZOXamdxZUOyzrdzLdLdTxZ1TKdr4/SI0sgLLI8sMTtSpoV1n2JCYQ61ByQXonb3c5O
pCuxWCG9TaO/Q5U59LNCczEYMD2Q2nmJly8JDa89K2vNiwE2FeYd7zpmy0iItqY6yZuWd+MKaYa+53WdfK5Tn02XycWHBN80FurcK1dzncrYuBf8K6R5pDj25y1hd5RwvA2Tk2ANpW9Wvl
vU2dgb5wRl4cl5YqhchcqaeQcnfex9l2/W3P6WarMKHhBhc1jwZaVp3UmRuUJqwb/UOxh1HotcKJ0JqXCYF0LgqqgeOql6V4xUjCKPxjHRaBVM9E9D3FB06DrDLphGxgoKMZHO3qGH8LMN
nfzZcbTrTqi+RkwAWYbjxyi3GaYWA46zgOKdEhe4tY7y7C7aevWZEHdpkrYMmpsMnMnDoK655/UT65juTtlX8X9Q3ktkcan34yM5EmxWz0w2roTYrW48g2zCbSEOAys=
  on:
    tags: True
    # condition: -z $SOURCEDEPLOY
