language: python

addons:
  apt:
    packages:
    - swig

python:
    - '2.7'
    - '3.6'

before_script:
    # - git clone https://c625a677ff258e52690537553ba18a1b845070be@github.com/equinor/xtgeo-testdata.git ../xtgeo-testdata
    - git clone https://git@github.com/equinor/xtgeo-testdata.git ../xtgeo-testdata

script:
    - make cc
    - make dist
    - make test


jobs:
  include:
    if: tag IS present

    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
