name: Run tests on selected images

on:
  pull_request:
    branches: [master]

env:
  CIBW_BEFORE_ALL_LINUX: "sh scripts/swig_manylinux.sh"
  CIBW_BEFORE_ALL_WINDOWS: "choco install -y --no-progress --allow-empty-checksums -r swig --version=4.0.1"
  CIBW_BEFORE_ALL_MACOS: "brew install swig"
  CIBW_TEST_COMMAND: pytest
  CIBW_BUILD: |
    cp36-manylinux_x86_64

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.5

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

      - name: Check wheels and paths (ubuntu only)
        run: |
          ls -l wheelhouse
          echo $PWD
          uname -a
          ls -latr
        if: matrix.os == 'ubuntu-18.04'
